# Collaboration: skill dependencies and composition

name: docs-refresh
version: "2.0.0"

dependencies:
  - skill: create-skill
    direction: inbound
    required: false
    reason: "After creating a new skill, run 'task docs:refresh' to regenerate docs"

composition:
  - when: "Creating a new skill"
    sequence:
      - create-skill
      - docs-refresh

  - when: "Modifying skill metadata (description, kind, tags)"
    sequence:
      - docs-refresh

  - when: "Removing a skill"
    sequence:
      - docs-refresh

triggers:
  - pattern: "documentation|docs refresh|update docs|sync docs|/docs-refresh"
    suggest: docs-refresh
  - condition: ".claude/skills/*/skill.yaml modified"
    action: "Run 'task docs:refresh' to regenerate REFERENCE.md and CLAUDE.md table"
  - condition: "Skill directory added or removed"
    action: "Run 'task docs:refresh' to update generated docs"

complements:
  - skill: create-skill
    relationship: "After creating a skill, docs-refresh regenerates reference docs"
  - skill: setup
    relationship: "After setup, docs-refresh verifies generated docs are current"

boundaries:
  owns:
    - "docs/skills/REFERENCE.md generation"
    - "CLAUDE.md skills table (between SKILLS_TABLE markers)"
  defers_to:
    - "Skill scaffolding -> create-skill"
    - "Committing documentation changes -> commit"
    - "CLAUDE.md sections outside markers -> manual editing"
  extension_points:
    - "Additional generated doc sections can be added to the refresh pipeline"

workflow:
  after_skill_change:
    description: "Standard workflow after modifying any skill"
    steps:
      - "Run 'task docs:refresh'"
      - "Verify with 'task docs:refresh-check'"
      - "Review git diff on generated files"
      - "Commit generated docs with skill changes"
